name: Validate code angular

on:
  pull_request:
    branches: ["main", "development", "staging"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: [16.17.1]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install project
        run: npm install
      
      - name: Build
        run: npm run build
